#!/bin/sh
mount -t proc none /proc
mount -t sysfs none /sys
mount -t tmpfs none /tmp
mount -t devtmpfs none /dev
ip addr add 192.168.76.20/24 dev eth0
ip link set eth0 up
ip route add default via 192.168.76.2 dev eth0
mkdir /tmp/rootfs
mount -t ext2 /dev/vda /tmp/rootfs
exec switch_root /tmp/rootfs/ /init