#!/bin/sh
mount -t proc none /proc
mount -t sysfs none /sys
mount -t tmpfs none /tmp
mount -t devtmpfs none /dev
mkdir /dev/pts/
mount -t devpts none /dev/pts/
if test -f "/etc/init.d/binfmt-support"; then
    echo "Starting BINFMT"
    /etc/init.d/binfmt-support start
fi
mkdir -m 777 /tmp/creds/
mount -t 9p -o trans=virtio creds /tmp/creds/ -oversion=9p2000.L,posixacl,cache=loose

mkdir -m 777 /tmp/build/
mount -t 9p -o trans=virtio build /tmp/build/ -oversion=9p2000.L,posixacl,cache=loose

setsid sh -c 'exec bash </dev/ttyAMA0 >/dev/ttyAMA0 2>&1'